version: '3'
services:
  app:
    image: vutientrinh0410/notes:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo_db:27017
      - DB_NAME = node
    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
