# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run CI/CD

on:
  push:
    # paths:
    #   - "!README.md"
    #   - "**.js"
    branches:
      - "main"

  # pull_request:
  #   branches: ["main"]

  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: "Name to greet"
  #       required: true
  #       default: "World"

  # schedule:
  #   - cron: '0 0 * * *'  # Every day at midnight
jobs:
  buiding:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test

      # - uses: actions/checkout@v4
      # - name: Login to DockerHub
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # - name: Build the Docker Image
      #   run: docker build -t vutientrinh0410/notes:latest .
      # - name: Docker Push
      #   run: docker push vutientrinh0410/notes:latest
